set(expected_dir "${EXPECTED_BIN}")
if(WIN32)
    string(TOLOWER "${expected_dir}" expected_dir)
endif()
foreach(artifact "${PLAYER}" "${CORE}" "${EXPECTED_BIN}/imPlayerTests.exe")
    if(NOT EXISTS "${artifact}")
        message(FATAL_ERROR "Missing build artifact: ${artifact}")
    endif()
    get_filename_component(output_dir "${artifact}" DIRECTORY)
    if(WIN32)
        string(TOLOWER "${output_dir}" output_dir)
    endif()
    if(NOT output_dir STREQUAL expected_dir)
        message(FATAL_ERROR "Incorrect output directory: ${artifact}")
    endif()
endforeach()
foreach(plugin IN LISTS PLUGIN_TARGETS)
    if(NOT EXISTS "${EXPECTED_BIN}/plugins/${plugin}.ipdplus")
        message(FATAL_ERROR "Missing decoder plugin: ${plugin}")
    endif()
endforeach()
if(EXISTS "${SOURCE_ROOT}/include" OR EXISTS "${SOURCE_ROOT}/test")
    message(FATAL_ERROR "Legacy source directories still exist")
endif()
file(GLOB test_entries LIST_DIRECTORIES TRUE "${SOURCE_ROOT}/src/test/*")
foreach(entry IN LISTS test_entries)
    if(IS_DIRECTORY "${entry}")
        message(FATAL_ERROR "Test sources must be flat: ${entry}")
    endif()
endforeach()

execute_process(COMMAND "${PLAYER}" --ld
    WORKING_DIRECTORY "${EXPECTED_BIN}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors
    TIMEOUT 30
)
if(NOT result EQUAL 0 OR NOT errors STREQUAL "")
    message(FATAL_ERROR "Decoder host failed (${result}): ${errors}")
endif()
string(FIND "${output}" "dr_wav Decoder" native_pos)
if(native_pos EQUAL -1)
    message(FATAL_ERROR "Native decoder not registered: ${output}")
endif()
file(READ "${EXPECTED_BIN}/config/plugin.config" plugin_config)
string(JSON count LENGTH "${plugin_config}" plugins)
if(count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON plugin_name GET "${plugin_config}" plugins ${index} name)
        string(FIND "${output}" "${plugin_name}" plugin_pos)
        if(plugin_pos EQUAL -1)
            message(FATAL_ERROR "Configured plugin not loaded: ${plugin_name}\n${output}")
        endif()
    endforeach()
endif()
