if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(LIBVGM_ARCH x64)
else()
    set(LIBVGM_ARCH x86)
endif()

set(LIBVGM_ROOT "${THIRDLIB_ROOT}/libvgm")

find_path(LIBVGM_INCLUDE_DIR
    NAMES player/playerbase.hpp
    PATHS
        ${LIBVGM_ROOT}
    NO_DEFAULT_PATH
)

set(LIBVGM_DEBUG_LIB_DIR "${LIBVGM_ROOT}/build/Debug/${LIBVGM_ARCH}")
set(LIBVGM_RELEASE_LIB_DIR "${LIBVGM_ROOT}/build/Release/${LIBVGM_ARCH}")

find_library(LIBVGM_PLAYER_LIBRARY_DEBUG
    NAMES vgm-player
    PATHS ${LIBVGM_DEBUG_LIB_DIR}
    NO_DEFAULT_PATH
)
find_library(LIBVGM_PLAYER_LIBRARY_RELEASE
    NAMES vgm-player
    PATHS ${LIBVGM_RELEASE_LIB_DIR}
    NO_DEFAULT_PATH
)

find_library(LIBVGM_EMU_LIBRARY_DEBUG
    NAMES vgm-emu
    PATHS ${LIBVGM_DEBUG_LIB_DIR}
    NO_DEFAULT_PATH
)
find_library(LIBVGM_EMU_LIBRARY_RELEASE
    NAMES vgm-emu
    PATHS ${LIBVGM_RELEASE_LIB_DIR}
    NO_DEFAULT_PATH
)

find_library(LIBVGM_AUDIO_LIBRARY_DEBUG
    NAMES vgm-audio
    PATHS ${LIBVGM_DEBUG_LIB_DIR}
    NO_DEFAULT_PATH
)
find_library(LIBVGM_AUDIO_LIBRARY_RELEASE
    NAMES vgm-audio
    PATHS ${LIBVGM_RELEASE_LIB_DIR}
    NO_DEFAULT_PATH
)

find_library(LIBVGM_UTILS_LIBRARY_DEBUG
    NAMES vgm-utils
    PATHS ${LIBVGM_DEBUG_LIB_DIR}
    NO_DEFAULT_PATH
)
find_library(LIBVGM_UTILS_LIBRARY_RELEASE
    NAMES vgm-utils
    PATHS ${LIBVGM_RELEASE_LIB_DIR}
    NO_DEFAULT_PATH
)

find_package(ZLIB REQUIRED)
find_package(Iconv REQUIRED)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Libvgm
    REQUIRED_VARS
        LIBVGM_INCLUDE_DIR
        LIBVGM_PLAYER_LIBRARY_DEBUG
        LIBVGM_PLAYER_LIBRARY_RELEASE
        LIBVGM_EMU_LIBRARY_DEBUG
        LIBVGM_EMU_LIBRARY_RELEASE
        LIBVGM_AUDIO_LIBRARY_DEBUG
        LIBVGM_AUDIO_LIBRARY_RELEASE
        LIBVGM_UTILS_LIBRARY_DEBUG
        LIBVGM_UTILS_LIBRARY_RELEASE
)

if(Libvgm_FOUND)
    add_library(Libvgm::Libvgm INTERFACE IMPORTED)
    set_target_properties(Libvgm::Libvgm PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${LIBVGM_INCLUDE_DIR}"
        INTERFACE_LINK_LIBRARIES
            "$<$<CONFIG:Debug>:${LIBVGM_PLAYER_LIBRARY_DEBUG};${LIBVGM_EMU_LIBRARY_DEBUG};${LIBVGM_AUDIO_LIBRARY_DEBUG};${LIBVGM_UTILS_LIBRARY_DEBUG}>;$<$<NOT:$<CONFIG:Debug>>:${LIBVGM_PLAYER_LIBRARY_RELEASE};${LIBVGM_EMU_LIBRARY_RELEASE};${LIBVGM_AUDIO_LIBRARY_RELEASE};${LIBVGM_UTILS_LIBRARY_RELEASE}>;ZLIB::ZLIB;Iconv::Iconv"
    )
endif()
